fix(frontend): Big and small accessibility improvements
jsr-io/jsr pull request #592
Opened 2024-06-03 18:35 UTC by timharek

This PR includes a bunch of big and small accessibility improvements spread across the whole frontend-part of JSR.

If you have any questions please let me know :)

Here is a list of what I've changed, fixed and improved:

- Removed all alt-text from the logos on the frontpage.
  - Since they are purely decoration they only add noise to a screen reader, eg: "Works with any runtime... <paragraph>... Deno logo. Bun logo." etc.
- Moved the timestamp in the footer inside a [`<time>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time)-element.
- Replaced the `type="text"` for global and symbol search with `type="search"`.
- Fixed contrasting colors a bunch of different places
  - This is the one I'm most uncertain of because I don't know if you are attached to the failing colors, if they are coming from a design system or something similar.
- Fixed the "Powered by Orama" string, the screen reader was reading just "Powered by"
- Added `aria-label` to the logo/home item in the navbar.
- Added `aria-hidden` to a bunch of icons and other misc. stuff that are purely decorative.
  - As well as the canvas on the frontpage.
- Fixed "Works with" on the package page. Now it reads everything in one go instead of the full phrase: "This package works with Deno" + "This package works with Bun" etc.
- Added `aria-label` to the tooltip.
- Made @<scope>/<package> assessible with screen reader in PackageHeader

Again, if you have any questions or additions, please let me know! :)

2024-06-03 18:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jsr-io/jsr?pullRequest=592) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jsr-io/jsr?pullRequest=592) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jsr-io/jsr?pullRequest=592) it.</sub>

2024-06-04 20:18 UTC, josh-collinsworth requested changes
This generally looks good, from review of the code. One nit, however: I would personally prefer that instances of `aria-label="foo"` be replaced with inner text using the `.sr-only` class instead, anywhere it makes sense to do so, like this:

```html
<span class="sr-only">Text that was previously inside the aria-label attribute on the parent element</span>
```

While `aria-label="foo"` is useful for AT users, actual text on the page as `<span class="sr-only">foo</span>` accomplishes the same task, but is better for i18n/translations, since browsers can usually more easily translate content than attribute values. (It can sometimes be better in reader mode situations as well.)

2024-06-04 20:32 UTC, timharek commented
Thank you for the feedback, @josh-collinsworth!

> While aria-label="foo" is useful for AT users, actual text on the page as <span class="sr-only">foo</span> accomplishes the same task, but is better for i18n/translations, since browsers can usually more easily translate content than attribute values. (It can sometimes be better in reader mode situations as well.)

I didn't know this, thanks for letting me know! ☺️ 

> I would personally prefer that instances of `aria-label="foo"` be replaced with inner text using the `.sr-only` class instead, anywhere it makes sense to do so

I have updated the PR now with all the places I think that makes sense, and works. An example of where I think it doesn't fit is in `PackageHeader` without adding more `aria-hidden="true"` to normal text inside of the different links for repo, scope, package etc.

Let me know if you have any further suggestions or feedback!

2024-06-07 14:04 UTC, josh-collinsworth approved these changes

2024-06-07 14:05 UTC, lucacasonato commented
Thanks @timharek!

2024-06-07 14:12 UTC, merged